"""first init db

Revision ID: ad55963cba61
Revises: None
Create Date: 2018-01-21 18:10:40.900472

"""

# revision identifiers, used by Alembic.
revision = 'ad55963cba61'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.VARCHAR(length=50), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
